live_config_reload = true

[env]
TERM = "xterm-256color"

[colors.bright]
black = '#555555'
blue = '#5555ff'
cyan = '#55ffff'
green = '#55ff55'
magenta = '#ff55ff'
red = '#ff5555'
white = '#ffffff'
yellow = '#ffff55'

[colors.cursor]
cursor = '#53ae71'
text = '#000000'

[colors.normal]
black = '#000000'
blue = '#5555cc'
cyan = '#7acaca'
green = '#55cc55'
magenta = '#cc55cc'
red = '#cc5555'
white = '#cccccc'
yellow = '#cdcd55'

[colors.primary]
background = '#111111'
foreground = '#b3b3b3'

[colors.selection]
background = '#4d52f8'
text = '#000000'

[cursor]
style = "Block"

[font]
size = 12

[font.normal]
family = "JetBrainsMono Nerd Font Mono"
style = "Regular"

[font.bold]
family = "JetBrainsMono Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font Mono"
style = "Bold Italic"

[window]
dynamic_padding = false
dynamic_title = true
