#!/usr/bin/env zsh

ssh-keygen -t ed25519 -C 120286670+blitzhetz@users.noreply.github.com -f ~/.ssh/id_ed25519

eval "$(ssh-agent -s)"

touch ~/.ssh/config

echo "Host *\n  AddKeysToAgent yes\n  IdentityFile ~/.ssh/id_ed25519" | tee ~/.ssh/config

ssh-add ~/.ssh/id_ed25519

pbcopy < ~/.ssh/id_ed25519.pub

echo "SSH is generated and copied."
